#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BlogApp.Resource", IsApplication=true)]

namespace BlogApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int beijing = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int berlin = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int berlin2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int biankuang1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int biankuang4 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int BobMinions = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int dikuang2 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ForbiddenCity = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int minionsBob = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int minionsBob2 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int paris = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int paris2 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int roma = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int roma2 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int splash = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int tokyo = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int tokyo2 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int travel = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int venice = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int venice2 = 2130837523;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060015
			public const int button1 = 2131099669;
			
			// aapt resource value: 0x7f060005
			public const int callBtn = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int editText1 = 2131099656;
			
			// aapt resource value: 0x7f06000d
			public const int emailBtn = 2131099661;
			
			// aapt resource value: 0x7f060013
			public const int icon = 2131099667;
			
			// aapt resource value: 0x7f06000e
			public const int imageView1 = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int imageView2 = 2131099663;
			
			// aapt resource value: 0x7f060016
			public const int item1 = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int item2 = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int item3 = 2131099672;
			
			// aapt resource value: 0x7f060014
			public const int itemName = 2131099668;
			
			// aapt resource value: 0x7f060012
			public const int listView1 = 2131099666;
			
			// aapt resource value: 0x7f060009
			public const int smsBtn = 2131099657;
			
			// aapt resource value: 0x7f060001
			public const int tableLayout1 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int tableRow1 = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int tableRow2 = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public const int tableRow3 = 2131099658;
			
			// aapt resource value: 0x7f060011
			public const int textView1 = 2131099665;
			
			// aapt resource value: 0x7f060003
			public const int textView10 = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int textView11 = 2131099655;
			
			// aapt resource value: 0x7f06000b
			public const int textView13 = 2131099659;
			
			// aapt resource value: 0x7f060004
			public const int textView14 = 2131099652;
			
			// aapt resource value: 0x7f06000c
			public const int textView15 = 2131099660;
			
			// aapt resource value: 0x7f060000
			public const int textView16 = 2131099648;
			
			// aapt resource value: 0x7f060010
			public const int title = 2131099664;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int connectLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int destinationCity = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int destinationLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int listViewDis = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int splash = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int visitedCity = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int visitedLayout = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int menu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
